apiVersion: batch/v1
kind: Job
metadata:
  name: setup
  labels: 
    name: deploy-task
spec:
  template:
    metadata:
      name: setup
      labels: 
        name: deploy-task
    spec:
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir: {}
        - name: tmp-pod
          emptyDir: {}

      containers:
        - name: setup
          image: asia.gcr.io/${PROJECT_NAME}/${CLOUD_REGISTRY_NAME}/app:$CIRCLE_SHA1
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "start migration"
              sleep 2s
              trap "touch /tmp/pod/terminated && echo 'terminated file was created'" EXIT
              bundle exec rails db:create && bundle exec rails db:migrate
              echo "finished migration"
             
          # command: ["./k8s/gke_rails_puma/deploy-task.sh"]
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-password
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-password
                  key: password
          volumeMounts:
            - mountPath: /tmp/pod
              name: tmp-pod

        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "start connect cloud proxy"
              /cloud_sql_proxy -instances=testing-190408-237002:asia-northeast1:rails-gke-sample-sql=tcp:3306 -credential_file=/secrets/cloudsql/credentials.json &
              CHILD_PID=$!
              echo "LATEST_BACKGROUND_PID : $!"
              ps
              ls /tmp
              ls /tmp/pod
              echo "CHILD_PID : $CHILD_PID"
              (while true; do if [[ -f "/tmp/pod/terminated" ]]; then kill $CHILD_PID; echo "Killed $CHILD_PID because the main container terminated."; fi; sleep 1; done) &
              wait $CHILD_PID
              if [[ -f "/tmp/pod/terminated" ]]; then exit 0; echo "Job completed. Exiting..."; fi
              echo "fuga"
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
            - name: tmp-pod
              mountPath: /tmp/pod  
              readOnly: true

      restartPolicy: Never
