apiVersion: batch/v1
kind: Job
metadata:
  name: setup
  labels: 
    name: deploy-task
spec:
  template:
    metadata:
      name: setup
      labels: 
        name: deploy-task
    spec:
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir: {}

      containers:
        - name: setup
          image: asia.gcr.io/${PROJECT_NAME}/${CLOUD_REGISTRY_NAME}/app:$CIRCLE_SHA1
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 2s
              bundle exec rails db:create && bundle exec rails db:migrate 
             
          # command: ["./k8s/gke_rails_puma/deploy-task.sh"]
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-password
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-password
                  key: password

        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=<INSTANCE_CONNECTION_NAME>=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql


      restartPolicy: Never
