kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  labels:
    type: gke-volume
    failure-domain.beta.kubernetes.io/zone: asia-northeast1-a
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  selector:
    matchLabels:
      type: gke-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi